-- 音声の編集（フォーカス）の「設定」を持つ表 audio_edits を作る（編集機能・段階2）
--
-- 目的：編集画面で選んだ範囲（時間×周波数・下げ方）を、あとで直せるように保存する。
--   ・設定（この表）は、作った本人だけが見られる。ログインなしの人にも、他の人にも、見えない
--   ・書き出した音（MP3）と、その解析結果（detections の記録）は、ふつうの録音と同じように、みんなに見える。
--     元の録音との関係は、ファイル名（<元の名前>_e<連番>.mp3）で分かる。この表には、公開されない情報（設定）だけを持つ
-- 状態：
--   ・保存だけ           ：exported_wav_filename も published_at も空。何度でも直せる・消せる
--   ・書き出し（解析済み）：exported_wav_filename あり・published_at 空。MP3 を保管場所に保存して、解析までした状態。直せる・消せる
--   ・公開               ：published_at あり。記録を登録して、みんなに見える状態。**もう、直せない・消せない**（公開した録音と、ずれないように）
-- 変わらないもの：detections・bird_master・verifications・保管場所の権限・Streamlit。新しい表を作るだけ。
--
-- 元に戻す：ファイルの末尾の「ロールバック」を参照

create table public.audio_edits (
  id bigint generated by default as identity primary key,

  source_wav_filename text not null,       -- 元の録音（bird-wav のファイル名。例 260712_043_Tr1.mp3）
  seq integer not null check (seq >= 1),   -- 連番（書き出すファイル名＝<元の名前>_e<連番>.mp3）

  t0_sec real not null,                    -- 取り出す時間の範囲（秒）
  t1_sec real not null,
  f_lo_hz real not null,                   -- 残す周波数の範囲（Hz）
  f_hi_hz real not null,
  settings jsonb not null default '{}'::jsonb, -- 下げ方の設定（mode・steep・strengthDb・octaveDb・floorDb・normalize など）

  exported_wav_filename text,              -- 書き出した MP3 の名前（例 260712_043_Tr1_e1.mp3）。空＝まだ書き出していない
  published_at timestamptz,                -- 記録を登録して、公開した日時。空＝まだ公開していない

  created_by uuid not null default auth.uid() references auth.users (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint audio_edits_range_ok check (t1_sec > t0_sec and f_hi_hz > f_lo_hz),
  constraint audio_edits_name_ok check (
    exported_wav_filename is null or exported_wav_filename ~ '^[A-Za-z0-9._-]+_e[0-9]+\.mp3$'
  ),
  -- 同じ録音に、同じ連番は、1つだけ（書き出すファイル名が、重ならないように）
  constraint audio_edits_seq_unique unique (source_wav_filename, seq),
  constraint audio_edits_exported_unique unique (exported_wav_filename)
);

create index audio_edits_source_idx on public.audio_edits (source_wav_filename);

-- ---------- 行の制限（RLS） ----------
alter table public.audio_edits enable row level security;

-- 読む：作った本人だけ
create policy audio_edits_read_own on public.audio_edits
  for select to authenticated
  using (created_by = (select auth.uid()));

-- 作る：管理者名簿にいる本人だけ（書き出し・公開は、管理者だけができるため）
create policy audio_edits_insert_own on public.audio_edits
  for insert to authenticated
  with check (
    created_by = (select auth.uid())
    and exists (select 1 from public.app_admins a where a.user_id = (select auth.uid()))
  );

-- 直す・消す：本人の、まだ公開していないものだけ（公開したら、もう変えられない）
create policy audio_edits_update_own_unpublished on public.audio_edits
  for update to authenticated
  using (created_by = (select auth.uid()) and published_at is null)
  with check (created_by = (select auth.uid()));

create policy audio_edits_delete_own_unpublished on public.audio_edits
  for delete to authenticated
  using (created_by = (select auth.uid()) and published_at is null);

-- ---------- 列ごとの権限 ----------
-- ログインなしの人には、何も渡さない。ログイン中は、読む・作る・直す・（未公開のものを）消す
revoke all on table public.audio_edits from anon, authenticated;

grant select on public.audio_edits to authenticated;

grant insert (
  source_wav_filename, seq, t0_sec, t1_sec, f_lo_hz, f_hi_hz, settings,
  exported_wav_filename, published_at, updated_at
) on public.audio_edits to authenticated;

grant update (
  t0_sec, t1_sec, f_lo_hz, f_hi_hz, settings,
  exported_wav_filename, published_at, updated_at
) on public.audio_edits to authenticated;

grant delete on public.audio_edits to authenticated;

-- ---------- ロールバック（元に戻す場合） ----------
-- drop table public.audio_edits;
