-- 別のモデル（Perch）の「意見」を持つ表 model_opinions を作る
--
-- 目的：BirdNET の記録に対して、別のモデル（Perch 2.0）が、同じ録音の同じ時間で、どの鳥を上位にしたかを持つ。
--       確認画面で、確定・修正・除外を決めるときの参考にする（「別モデルの意見」）。
--   ・1行＝録音の5秒の区間の、上位の1種（rank 1〜5）。点数は、logit（確かな検出は 9〜12・雑音は 4〜7 の目安）と、確率（絞った種のなかでの softmax）
--   ・鳥の名前は、BirdNET の学名に直したもの（例：Perch の Parus major → BirdNET の Parus minor）。日本語名つき
--   ・読める・書ける・消せるのは、管理者名簿にいる人だけ。ログインなしの人にも、ほかの人にも、見えない（当面は管理者だけに見せる方針）
-- 変わらないもの：detections・verifications・audio_edits・保管場所の権限・Streamlit。新しい表を作るだけ。
--
-- 元に戻す：ファイルの末尾の「ロールバック」を参照

create table public.model_opinions (
  id bigint generated by default as identity primary key,

  wav_filename text not null,              -- 録音（bird-wav のファイル名。例 260905_011_1103.mp3）
  model_name text not null,                -- 例 Perch
  model_version text not null,             -- 例 2.0
  t0_sec real not null,                    -- 区間（秒）。Perch は5秒ごと
  t1_sec real not null,
  rank smallint not null check (rank between 1 and 10),  -- その区間の順位（1が一番高い）
  scientific_name text not null,           -- BirdNET の学名に直したもの
  common_name text,                        -- 日本語名（BirdNET のラベルから）
  logit real,                              -- モデルの点数（補正されていない）
  prob real,                               -- 場所・時期で絞った種のなかでの確率（softmax）
  analyzed_at timestamptz,
  params jsonb,                            -- 設定（バリアント・区間の長さ・場所の絞り込みなど）

  created_by uuid not null default auth.uid() references auth.users (id),
  created_at timestamptz not null default now(),

  constraint model_opinions_range_ok check (t1_sec > t0_sec),
  -- 同じ録音・モデル・区間・順位は、1行だけ（やり直すと、上書き）
  constraint model_opinions_unique unique (wav_filename, model_name, t0_sec, rank)
);

create index model_opinions_file_idx on public.model_opinions (wav_filename);

-- ---------- 行の制限（RLS）：管理者名簿にいる人だけ ----------
alter table public.model_opinions enable row level security;

create policy model_opinions_admin_select on public.model_opinions
  for select to authenticated
  using (exists (select 1 from public.app_admins a where a.user_id = (select auth.uid())));

create policy model_opinions_admin_insert on public.model_opinions
  for insert to authenticated
  with check (
    created_by = (select auth.uid())
    and exists (select 1 from public.app_admins a where a.user_id = (select auth.uid()))
  );

create policy model_opinions_admin_update on public.model_opinions
  for update to authenticated
  using (exists (select 1 from public.app_admins a where a.user_id = (select auth.uid())))
  with check (exists (select 1 from public.app_admins a where a.user_id = (select auth.uid())));

-- やり直すとき、古い区間の行が残らないよう、管理者は消せる（Perch の意見は、解析から作り直せる派生データ）
create policy model_opinions_admin_delete on public.model_opinions
  for delete to authenticated
  using (exists (select 1 from public.app_admins a where a.user_id = (select auth.uid())));

-- ---------- 列ごとの権限 ----------
revoke all on table public.model_opinions from anon, authenticated;

grant select on public.model_opinions to authenticated;
grant insert (
  wav_filename, model_name, model_version, t0_sec, t1_sec, rank,
  scientific_name, common_name, logit, prob, analyzed_at, params
) on public.model_opinions to authenticated;
grant update (
  model_version, t1_sec, scientific_name, common_name, logit, prob, analyzed_at, params
) on public.model_opinions to authenticated;
grant delete on public.model_opinions to authenticated;

-- ---------- ロールバック（元に戻す場合） ----------
-- drop table public.model_opinions;
