-- 修正・確定（人の判断）を持つ表 verifications を作る（Phase 2-A）
--
-- なぜ別の表か：BirdNET の解析結果（detections）は、Streamlit の「データ登録」のたびに、同じ記録が上書きされる
-- （on_conflict = wav_filename,start_sec,end_sec,scientific_name）。人が確定・修正した内容を detections に直接
-- 書くと、次の取り込みで消えてしまうため、別の表に持ち、画面で重ねて表示する。
--
-- 適用前の状態には影響しない：新しい表を作るだけで、detections・bird_master・Streamlit は変わらない。
-- 元に戻す：drop table public.verifications;

create table public.verifications (
  id bigint generated by default as identity primary key,

  -- どの記録か。取り込みで上書きされても、ずれないよう、ファイル名・区間・元の鳥で探す
  wav_filename text not null,
  start_sec real not null,
  end_sec real not null,
  original_scientific_name text not null,
  original_common_name text,

  -- 人の判断：confirmed＝確定（この鳥で合っている）／corrected＝修正（別の鳥だった）／rejected＝除外（誤検出）
  status text not null check (status in ('confirmed', 'corrected', 'rejected')),
  verified_common_name text,
  verified_scientific_name text,
  method text check (method in ('heard', 'seen', 'photo')), -- 根拠：耳／目／写真（本人だけに見える）
  note text, -- メモ（本人だけに見える）

  verified_by uuid not null default auth.uid() references auth.users (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint verifications_corrected_needs_species
    check (status <> 'corrected' or verified_common_name is not null),
  -- 1人が、同じ記録に付ける判断は1つ（上書き）。将来パートナーが増えても、人ごとに持てる
  constraint verifications_one_per_user_and_record
    unique (verified_by, wav_filename, start_sec, end_sec, original_scientific_name)
);

create index verifications_wav_idx on public.verifications (wav_filename);

-- ---------- 行の制限（RLS） ----------
alter table public.verifications enable row level security;

-- 読むのは誰でも（読める列は、下の権限で絞る）
create policy verifications_read on public.verifications
  for select to anon, authenticated
  using (true);

-- 書く・直す・消すのは、ログイン中の本人の行だけ
create policy verifications_insert_own on public.verifications
  for insert to authenticated
  with check (verified_by = (select auth.uid()));

create policy verifications_update_own on public.verifications
  for update to authenticated
  using (verified_by = (select auth.uid()))
  with check (verified_by = (select auth.uid()));

create policy verifications_delete_own on public.verifications
  for delete to authenticated
  using (verified_by = (select auth.uid()));

-- ---------- 列ごとの権限 ----------
revoke all on table public.verifications from anon, authenticated;

-- ログインなし：判断の結果（鳥の名前・確定の印）だけ読める。根拠・メモ・誰が・いつ、は読めない
grant select (
  wav_filename, start_sec, end_sec, original_scientific_name, original_common_name,
  status, verified_common_name, verified_scientific_name
) on public.verifications to anon;

-- ログイン中：全列を読める。書けるのは、判断の内容の列だけ（誰が・いつ、は自動で入る）
grant select on public.verifications to authenticated;

grant insert (
  wav_filename, start_sec, end_sec, original_scientific_name, original_common_name,
  status, verified_common_name, verified_scientific_name, method, note, updated_at
) on public.verifications to authenticated;

-- upsert（あれば上書き）は、送った列すべてを更新の対象にするため、insert と同じ列を許可する
grant update (
  wav_filename, start_sec, end_sec, original_scientific_name, original_common_name,
  status, verified_common_name, verified_scientific_name, method, note, updated_at
) on public.verifications to authenticated;

grant delete on public.verifications to authenticated;
